// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.5
// source: extraction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtractionService_Extract_FullMethodName = "/extraction.ExtractionService/Extract"
)

// ExtractionServiceClient is the client API for ExtractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtractionServiceClient interface {
	Extract(ctx context.Context, in *ExtractionRequest, opts ...grpc.CallOption) (*ExtractionResponse, error)
}

type extractionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractionServiceClient(cc grpc.ClientConnInterface) ExtractionServiceClient {
	return &extractionServiceClient{cc}
}

func (c *extractionServiceClient) Extract(ctx context.Context, in *ExtractionRequest, opts ...grpc.CallOption) (*ExtractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractionResponse)
	err := c.cc.Invoke(ctx, ExtractionService_Extract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractionServiceServer is the server API for ExtractionService service.
// All implementations must embed UnimplementedExtractionServiceServer
// for forward compatibility.
type ExtractionServiceServer interface {
	Extract(context.Context, *ExtractionRequest) (*ExtractionResponse, error)
	mustEmbedUnimplementedExtractionServiceServer()
}

// UnimplementedExtractionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtractionServiceServer struct{}

func (UnimplementedExtractionServiceServer) Extract(context.Context, *ExtractionRequest) (*ExtractionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedExtractionServiceServer) mustEmbedUnimplementedExtractionServiceServer() {}
func (UnimplementedExtractionServiceServer) testEmbeddedByValue()                           {}

// UnsafeExtractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractionServiceServer will
// result in compilation errors.
type UnsafeExtractionServiceServer interface {
	mustEmbedUnimplementedExtractionServiceServer()
}

func RegisterExtractionServiceServer(s grpc.ServiceRegistrar, srv ExtractionServiceServer) {
	// If the following call panics, it indicates UnimplementedExtractionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtractionService_ServiceDesc, srv)
}

func _ExtractionService_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionServiceServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionService_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionServiceServer).Extract(ctx, req.(*ExtractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtractionService_ServiceDesc is the grpc.ServiceDesc for ExtractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extraction.ExtractionService",
	HandlerType: (*ExtractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extract",
			Handler:    _ExtractionService_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extraction.proto",
}
